### PR TITLE
list of talks

### PR DESCRIPTION
**Pull request by caalberts**
@Tianster feel free to add to the list

### CODE REVIEW

**Comment by cbas** [comment]
LGTM thanks @caalberts !

/cc @rachlim90 Gonna keep track of the talks given by everyone.

**Comment by rachlim90** [comment]
@cbas @caalberts AWESOME

**Comment by caalberts** [comment]
Sorry typos on the file name

**Comment by cbas** [comment]
No worries @caalberts. Tip for next time: You can "fix up" commits with an interactive rebase. It lets you roll up this kind of spam into a single commit.

**Comment by jsstrn** [comment]
Cool! Thanks @caalberts!

**Comment by caalberts** [comment]
:+1: @cbas

**Pull request merged**
